### ISSUE TITLE
Everything Wrong With This Guide.

### ISSUE THREAD

**Issue by Sha8q** [emiyl/dsi.cfw.guide#3]
First, you don't make any proper nand backup, and that could make people restore a NAND with the no$ fooster in it.  There is no uninstalling section, and the helper scripts will never be perfected.  Just add the manual instillation HTML to the guide, or something for people that can't get it to work. https://www.mediafire.com/download/f8fty989cj8hur1

**Comment by jerbear64** [comment]
>First, you don't make any proper nand backup, and that could make people restore a NAND with the no$ fooster in it.

Non-issue. Modern versions of fwtool also create a dump with the NO$GBA footer on it.

>There is no uninstalling section

There is no public uninstaller for unlaunch. The only way to uninstall it would be with a hardmod or with TWLNF, and TWLNF is an unsafe tool when it comes to NAND modification.

>and the helper scripts will never be perfected. Just add the manual instillation HTML to the guide, or something for people that can't get it to work. 

Manual instructions are doable, but I'm not sure of the feasibility of adding them in an easy to understand manner. The typical end-user wouldn't know how to use a hex editor very well, and this can cause more problems than the helper script occasionally failling will.

Additionally the HTML here isn't necessarily written well, there's a reason dsiguide.me pulled it initially. I wouldn't be able to directly add it anyways as the guide uses Jekyll for static page generation.

For what it's worth I plan to add a second set of verification to the script to verify the end-results, although in most cases I've found the low-level formatting of the SD card to be at fault, which I can do nothing about; the end-user needs to ensure that they've formatted their SD card properly, and not as a quick format.

**Comment by Sha8q** [comment]
You clearly didn't get what I mean.  I want there to be proper NAND backups because restoring a proper NAND uninstalls Unlaunch.  FWTool 1.6.0 is needed for that.  When I said add the HTML, I meant copy the text and add it.  Verification scripts are not necessary, as users know if it doesn't work so it tells them what they already know.  Hex editors aren't that hard to use, and the first time I used one there was no problem at all.  You could add a .gif showing the steps if they don't understand the words.

**Comment by jerbear64** [comment]
This is a "proper" NAND backup, FWTool 2.0 generates a No$ footer as well now.
I'm not a fan of using a NAND backup to uninstall Unlaunch, that wastes NAND cycles and there's not necessarily a safe way to go about cleanly uninstalling it.

I will not be adding that HTML directly if I end up doing it. I'd absolutely reword it a bit because those specific instructions were relatively confusing even for me the first time around, not because hex editors are hard, but because those instructions can be explained better.

A .gif showing steps may be beneficial for the hex editor portions, and is something to consider.

I do plan to wrap the helper in an EXE for what it's worth, as most user error I've found is from Python version mismatches.

**Comment by Sha8q** [comment]
I've uninstalled Unlaunch successfully, and if the person does brick they can use a proper NAND backup to unbrick.

**Comment by jerbear64** [comment]
Yes, wasting NAND cycles in the process. It is very bad to reflash an entire 256m megabyte NAND backup just to change one small TMD file. A better option would be to see if nocash can add an uninstall option to the installer itself.

The DSi's NAND technology is nothing like modern SSD's, it can be worn out very easily.

**Comment by jerbear64** [comment]
As your antics on Discord have helped me prove, manual instructions are unnecessary. Both cases you attempted to solve with your manual instructions were simple fixes and user error.

The first case was easily fixed by replacing the menu with the DSiMenu++. The second was also user error, not moving the contents of the dump folder to SD. The old manual instructions would have solved neither.

You wasted users' time by making them do things the old way unnecessarily, which as I said it would, just caused more confusion in the process, and you wasted my time by arguing that the NAND backup isn't proper (and again... **it is**).

Closing.
