### ISSUE TITLE
Maketmd

### ISSUE THREAD

**Issue by hawkleee** [emiyl/dsi.cfw.guide#4]
I'm on the part of the guide where it shows you how to install dsiware, and I downloaded maketmd, but the application doesn't seem to work. I pressed the application through the bin64 and bin32 and it pops up for 2 seconds and closes. I'm not sure what I'm supposed to do. 

Also, I was confused on the sd card part in the "installing hiyacfw" guide. It says you need <2gb, so does that mean I need two sd cards? I didn't have any that was under 2gb, so I completed the page with an 8gb sd card. It gave me an error code at the end so I figured I should go to the dsimenu++ and got stuck on the maketmd part.

**Comment by jerbear64** [comment]
MakeTMD has no GUI. If you just double click the application it will immediately close due to not knowing what to make a TMD for. You must drag and drop a .app on to it, and it'll generate a TMD for it.

You're correct in that you only need one SD card, even if it's less than 2 GB. I will make this more clear on the guide.

**Comment by jerbear64** [comment]
65ae395 makes it more clear that a 2GB SD card is optional.

**Comment by hawkleee** [comment]
Thank you! That worked.

Just a last question, is it possible to completely wipe the unlauncher & hiyacfw and start from scratch? I may have confused myself on the guide and lost where I was at.

**Comment by jerbear64** [comment]
No safe way, no. Generally speaking it's okay to start from the HiyaCFW page again, though.
I'm closing this issue but will leave it open for comments.
